version: "3.8"
services:
  mongo:
    image: "mongo"
    volumes:
      - data:/data/db
    restart: always
    expose:
      - 27017
    networks:
      - docker_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - docker_network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - docker_network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - docker_network

volumes:
  data:
  node_modules:

networks:
  docker_network:
    driver: bridge
